name: Build

on:
  push:
    branches: [ master, Dmytro, Olesia, Vitaliy ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: settings
        run: go mod tidy
      
      - name: Run
        run: make

      - name: Test
        run: make test
        
      - name: Run out/example
        run: make out/example
      
      - name: Clean
        run: make clean
