name: Build

on:
  push:
    branches: [ master, Dmytro, Olesia, Vitaliy ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#######################################
      - name: Run
        run: make

      - name: Test
        run: make test
      
      - name: Clean
        run: make clean
